#!/usr/bin/Rscript
suppressMessages(library(methods))
suppressMessages(require("gitwords"))
args <- commandArgs(TRUE)
output <- ""
if(length(args)==3){
  output <- get_words(date=c(as.character(args[1]),as.character(args[2])),repo=as.character(args[3]))
} else if(length(args)==2){
  if(grepl("/",as.character(args[2]))==TRUE){
    output <- get_words(date=as.character(args[1]),repo=as.character(args[2]))
  } else {
    output <- get_words(date=c(as.character(args[1]),as.character(args[2])))
  }
} else if(length(args)==1) {
  if(grepl("/",as.character(args[1]))==TRUE){
    output <- get_words(repo=as.character(args[1]))
  } else {
    output <- get_words(date=as.character(args[1]))
  }
} else {
  output <- get_words()
}
print(output)
